Capstone Project Design
NickEmma/capstone-project-1 pull request #1
Opened 2022-06-18 12:30 UTC by NickEmma

### This is how i designed the webpage
- Added a github workflow
- Created a good file and folder structure
- Linked all files together

2022-06-22 11:42 UTC, arslanbisharat requested changes
Hi @NickEmma, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- The Pull Request has a proper title and description. ✔️
- You have added a descriptive Readme file. Good Job. ✔️
- There is no linter error is present. ✔️
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Please make sure you right descriptive comments. Commenting involves placing Human Readable Descriptions inside of computer programs detailing what the Code is doing. Proper use of commenting can make code maintenance much easier, as well as helping make finding bugs faster. Further, commenting is very important when writing functions that other people will use. :x:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-22 11:42 UTC, arslanbisharat commented on css/styles.css
> +#menu {
- [ ] According to Microverse guidelines, please avoid using id as a selector. ID selectors have a higher specificity than attribute selectors but using ids in css isn't recommended and can't be reused. CSS classes can do everything IDs can.

2022-06-22 11:42 UTC, arslanbisharat commented on about.html
> +            <a href="about.html">About</a>
- [ ] I can move from `Home `page to `About `page but if I have to move back to `Home `page from `About `page, I have to click on the logo. I would recommend you to please add a `Home `page button when someone is present on `About `page.

2022-06-22 11:42 UTC, arslanbisharat commented on about.html
> +      </div>
- [ ] The footer at the Home page doesn't have dropdown icon as present in the design. 
![image](https://user-images.githubusercontent.com/58504655/175020019-f528e832-66c1-4d48-a5c9-826c57a64e85.png)

2022-06-22 11:42 UTC, arslanbisharat commented on about.html
> +            anything else you can imagine. It was born as a proposition. As an
- [ ] The text layout doesn't meet the design provided by Microverse. 

Your Design: 
![image](https://user-images.githubusercontent.com/58504655/175020695-cd0d8732-c6c4-4a79-b84c-b0fe5e3926c1.png)

Original 
![image](https://user-images.githubusercontent.com/58504655/175020638-0e6574f4-bb33-47a8-8c0e-92a17ed8c680.png)

2022-06-22 12:02 UTC, NickEmma commented on css/styles.css
> +#menu {
okay

2022-06-22 12:13 UTC, NickEmma commented
I don't understand what you mean, like what you told me to do

On Wed, Jun 22, 2022, 12:43 PM Arslan Bisharat ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @NickEmma <https://github.com/NickEmma>,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> Highlights
>
>    - The Pull Request has a proper title and description. ✔️
>    - You have added a descriptive Readme file. Good Job. ✔️
>    - There is no linter error is present. ✔️
>    - Project has met all the technical aspects you needed for this
>    project. Keep rocking! ✔️
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> You can also consider:
>
>    - Please make sure you right descriptive comments. Commenting involves
>    placing Human Readable Descriptions inside of computer programs detailing
>    what the Code is doing. Proper use of commenting can make code maintenance
>    much easier, as well as helping make finding bugs faster. Further,
>    commenting is very important when writing functions that other people will
>    use. ❌
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In css/styles.css
> <https://github.com/NickEmma/capstone-project-1/pull/1#discussion_r903621148>
> :
>
> > +section {
>
> +  padding: 2rem 7%;
>
> +}
>
> +
>
> +.header {
>
> +  position: fixed;
>
> +  top: 0;
>
> +  left: 0;
>
> +  right: 0;
>
> +  z-index: 1;
>
> +  padding: 2rem 9%;
>
> +  background: rgb(212 208 208 / 9%);
>
> +  backdrop-filter: blur(5px);
>
> +}
>
> +
>
> +#menu {
>
>
>
>    - According to Microverse guidelines, please avoid using id as a
>    selector. ID selectors have a higher specificity than attribute selectors
>    but using ids in css isn't recommended and can't be reused. CSS classes can
>    do everything IDs can.
>
> ------------------------------
>
> In about.html
> <https://github.com/NickEmma/capstone-project-1/pull/1#discussion_r903625189>
> :
>
> > +          </li>
>
> +          <li>
>
> +            <a href="#">myPage</a>
>
> +          </li>
>
> +          <li>
>
> +            <a href="#">logOut</a>
>
> +          </li>
>
> +        </ul>
>
> +      </div>
>
> +      <nav class="navbar">
>
> +        <a href="index.html" class="logo">
>
> +          <img src="./assets/images/logo.svg" alt="" />
>
> +        </a>
>
> +        <ul>
>
> +          <li>
>
> +            <a href="about.html">About</a>
>
>
>
>    - I can move from Home page to About page but if I have to move back
>    to Home page from About page, I have to click on the logo. I would
>    recommend you to please add a Home page button when someone is present
>    on About page.
>
> ------------------------------
>
> In about.html
> <https://github.com/NickEmma/capstone-project-1/pull/1#discussion_r903630652>
> :
>
> > +    <footer class="footer about-footer" id="footer">
>
> +      <img src="./assets/images/creative_commons.svg" alt="logo" />
>
> +      <div>
>
> +        <p class="footer-title">
>
> +          2022 creative commons Portugal, all right reserved
>
> +        </p>
>
> +        <p class="copyright about-copyright">
>
> +          CC Bootcamp Summer 2022 works under the Creative Commons license which
>
> +          means that the content provided during the program will be under the
>
> +          same license. Refer to the Creative Commons page to read more about
>
> +          it.
>
> +        </p>
>
> +      </div>
>
>
>
>    - The footer at the Home page doesn't have dropdown icon as present in
>    the design.
>    [image: image]
>    <https://user-images.githubusercontent.com/58504655/175020019-f528e832-66c1-4d48-a5c9-826c57a64e85.png>
>
> ------------------------------
>
> In about.html
> <https://github.com/NickEmma/capstone-project-1/pull/1#discussion_r903635152>
> :
>
> > +          <p class="pfirst">
>
> +            The Creative Commons Bootcamp Summer 2022 was born in April 2015,
>
> +            not just as a programming foundation, a school, an Institute, or
>
> +            anything else you can imagine. It was born as a proposition. As an
>
>
>
>    - The text layout doesn't meet the design provided by Microverse.
>
> Your Design:
> [image: image]
> <https://user-images.githubusercontent.com/58504655/175020695-cd0d8732-c6c4-4a79-b84c-b0fe5e3926c1.png>
>
> Original
> [image: image]
> <https://user-images.githubusercontent.com/58504655/175020638-0e6574f4-bb33-47a8-8c0e-92a17ed8c680.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NickEmma/capstone-project-1/pull/1#pullrequestreview-1015003330>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQRCRRMGZFIP327HHASCCH3VQL34JANCNFSM5ZEWHJOA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-22 12:16 UTC, arslanbisharat commented
> I don't understand what you mean, like what you told me to do
> […](#)

Thank you so much for reaching out. I believe my requested changes are very clear. I would be happy to assist you and explain it to you. Can you please address what you didn’t understand? 
looking forward to hearing from you

2022-06-22 12:29 UTC, NickEmma commented
everything i don't understand everything do you've some time to spend like
10 - 15 minutes to explain on zoom if you don't mind

On Wed, 22 Jun 2022 at 13:16, Arslan Bisharat ***@***.***>
wrote:

> I don't understand what you mean, like what you told me to do
> … <#m_-8855743935038925785_>
>
> Thank you so much for reaching out. I believe my requested changes are
> very clear. I would be happy to assist you and explain it to you. Can you
> please address what you didn’t understand?
> looking forward to hearing from you
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NickEmma/capstone-project-1/pull/1#issuecomment-1163024918>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQRCRRPX5WNSMBBZ5JYVDOLVQL7ZZANCNFSM5ZEWHJOA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-22 12:40 UTC, NickEmma commented on about.html
> +            <a href="about.html">About</a>
i used the logo so that when the user clicks on the logo it should take them back to the home

2022-06-22 12:40 UTC, arslanbisharat commented on about.html
> +      </div>
There should be a drop down icon present after More text as given in the design

2022-06-22 12:40 UTC, arslanbisharat commented on about.html
> +            <a href="about.html">About</a>
When we are on about page instead of About button it should have Home button

2022-06-22 12:43 UTC, NickEmma commented
okay i have resolved the issue now i will put the icon on the more button

On Wed, 22 Jun 2022 at 13:40, Arslan Bisharat ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In about.html
> <https://github.com/NickEmma/capstone-project-1/pull/1#discussion_r903691484>
> :
>
> > +    <footer class="footer about-footer" id="footer">
> +      <img src="./assets/images/creative_commons.svg" alt="logo" />
> +      <div>
> +        <p class="footer-title">
> +          2022 creative commons Portugal, all right reserved
> +        </p>
> +        <p class="copyright about-copyright">
> +          CC Bootcamp Summer 2022 works under the Creative Commons license which
> +          means that the content provided during the program will be under the
> +          same license. Refer to the Creative Commons page to read more about
> +          it.
> +        </p>
> +      </div>
>
> There should be a drop down icon present after More text as given in the
> design
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NickEmma/capstone-project-1/pull/1#discussion_r903691484>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQRCRRKLHINTGN24HAV5KL3VQMCTZANCNFSM5ZEWHJOA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-22 12:51 UTC, NickEmma commented on about.html
> +            anything else you can imagine. It was born as a proposition. As an
i have changed it to the original color

2022-06-22 13:25 UTC, zieeco requested changes
Hi, @NickEmma ,


Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
_Check the comments under the review._

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-22 13:25 UTC, zieeco commented on css/styles.css
> +#menu {
**[REQUIRED CHANGES]**

- Hey, great job with your implementation, however, as required by the previous reviewer, kindly use a CSS class to style your `menu`, then use the id to target it using javascript. e.g ` <div id="menu" class="fas fa-bars menu-icon"></div>`

```
.menu-icon {/* put the style here*/ } or replace `#menu` with `.menu-icon`

2022-06-22 13:25 UTC, zieeco commented on about.html
> +            <a href="about.html">About</a>
@arslanbisharat, This is working correctly as when you click on the logo, it takes you back to the home page. 
**[OPTIONAL]**

- You could improve this ` <a href="index.html" class="logo">` to ` <a href="/" class="logo">` making it move to the home by default

2022-06-22 13:25 UTC, zieeco commented on about.html
> +      </div>
- [x] This issue is well resolved :heavy_check_mark:

2022-06-22 13:25 UTC, zieeco commented on about.html
> +            anything else you can imagine. It was born as a proposition. As an
- [ ] This issue is well resolved :heavy_check_mark:

2022-06-22 14:07 UTC, NickEmma commented on css/styles.css
> +#menu {
Okay i have resolved this issue

2022-06-22 14:35 UTC, merged

2022-10-14 11:54 UTC, NickEmma commented
@zieeco and @danmainah Thank you for reviewing and approving my code.